'use client'

import { useState } from 'react'
import { useAccount, useChainId, useConnect, useDisconnect, useSwitchChain } from 'wagmi'
import { ArrowDownUp, BarChart3, Check, ChevronDown, CircleHelp, Copy, Droplets, ExternalLink, History, LayoutDashboard, Menu, Plus, Settings2, ShieldCheck, Sparkles, Wallet, X, Zap } from 'lucide-react'
import { chainNames, explorerUrl, getRouterAddress, hasRouterConfig, hasTokenFactoryConfig, hasWalletConnectConfig, shortAddress, supportedChains } from '@/lib/wagmi'

const nav = [
  ['home','Home',LayoutDashboard], ['swap','Swap',ArrowDownUp], ['pools','Liquidity Pools',Droplets], ['farms','Farms',Zap], ['limit','Limit Orders',BarChart3], ['analytics','Analytics',BarChart3], ['bridge','Bridge',ExternalLink], ['create','Token Creator',Plus], ['history','Activity',History],
] as const
const tokens = [{ symbol:'ETH', name:'Ethereum', glyph:'◆', color:'eth' }, { symbol:'USDC', name:'USD Coin', glyph:'$', color:'usdc' }, { symbol:'BNB', name:'BNB Chain', glyph:'B', color:'bnb' }, { symbol:'ARB', name:'Arbitrum', glyph:'A', color:'arb' }]

type Token = typeof tokens[number]
function TokenIcon({ token }: { token: Token }) { return <span className={`token-icon ${token.color}`}>{token.glyph}</span> }

function WalletModal({ close }: { close: () => void }) {
  const { connectors, connect, isPending, error } = useConnect()
  const available = connectors.filter((connector, index, all) => all.findIndex((item) => item.id === connector.id) === index)
  return <div className="modal-backdrop" onClick={close}><div className="wallet-modal" onClick={(event) => event.stopPropagation()}><div className="modal-heading"><div><p className="eyebrow">Secure connection</p><h2>Connect wallet</h2></div><button className="icon-button" onClick={close} aria-label="Close wallet dialog"><X /></button></div><p className="modal-copy">Your keys stay with you. Connect to unlock real on-chain balances and transactions.</p><div className="wallet-options">{available.map((connector) => <button className="wallet-option" key={connector.uid} onClick={() => connect({ connector })} disabled={isPending}><span className="wallet-mark">{connector.name.toLowerCase().includes('injected') ? 'M/R' : 'W'}</span><span><strong>{connector.name.toLowerCase().includes('injected') ? 'MetaMask or Rabby' : connector.name}</strong><small>{connector.name.toLowerCase().includes('injected') ? 'Browser wallet extension' : 'Scan with your mobile wallet'}</small></span><ExternalLink /></button>)}</div>{!hasWalletConnectConfig && <p className="wallet-note"><CircleHelp /> Add NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID for mobile WalletConnect.</p>}{error && <p className="error-text">{error.message}</p>}</div></div>
}

function ConfigNotice({ kind = 'router' }: { kind?: 'router' | 'factory' }) { const ready = kind === 'router' ? hasRouterConfig : hasTokenFactoryConfig; return <div className={`config-notice ${ready ? 'ready' : ''}`}><ShieldCheck /><div><strong>{ready ? 'Contract configured' : 'Read-only configuration needed'}</strong><span>{ready ? 'Transactions will be signed by your connected wallet.' : `Set NEXT_PUBLIC_${kind === 'router' ? 'ROUTER' : 'TOKEN_FACTORY'}_ADDRESS or a chain-specific address to enable writes.`}</span></div></div> }

function SwapView({ openWallet }: { openWallet: () => void }) { const [amount, setAmount] = useState(''); return <div className="content-grid"><section className="panel swap-panel"><div className="panel-heading"><div><p className="eyebrow">Trade on-chain</p><h1>Swap tokens</h1></div><button className="icon-button"><Settings2 /></button></div><div className="route-chip"><span className="live-dot" /> Best route · Smart routing</div><div className="amount-box"><div className="field-label"><span>Sell</span><span>Balance — 0.00 ETH</span></div><div className="amount-row"><input aria-label="Amount to sell" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="0.00" inputMode="decimal" /><button className="token-select"><TokenIcon token={tokens[0]} /> ETH <ChevronDown /></button></div><div className="field-foot"><span>≈ $0.00</span><button onClick={() => setAmount('0.00')}>MAX</button></div></div><div className="swap-divider"><button className="switch-button" aria-label="Reverse swap"><ArrowDownUp /></button></div><div className="amount-box"><div className="field-label"><span>Buy</span><span>Balance — 0.00 USDC</span></div><div className="amount-row"><input aria-label="Amount to buy" readOnly value={amount ? '0.00' : ''} placeholder="0.00" /><button className="token-select"><TokenIcon token={tokens[1]} /> USDC <ChevronDown /></button></div><div className="field-foot"><span>1 ETH = $3,842.12</span><span className="positive">+0.24%</span></div></div><div className="trade-details"><span>Fee <b>0.25%</b></span><span>Slippage <b>0.5%</b></span><span>Router <b>{getRouterAddress(useChainId()) ? 'Configured' : 'Missing'}</b></span></div><ConfigNotice /><button className="primary-button full" onClick={openWallet}><Wallet /> Connect wallet to swap</button></section><aside className="panel side-panel"><div className="panel-heading"><div><p className="eyebrow">Market pulse</p><h2>Top tokens</h2></div><BarChart3 /></div>{tokens.map((token, index) => <div className="token-row" key={token.symbol}><TokenIcon token={token} /><span><strong>{token.symbol}</strong><small>{token.name}</small></span><span className="token-price">${index === 0 ? '3,842.12' : index === 1 ? '1.00' : index === 2 ? '622.40' : '1.17'}<small className="positive">+{index + 2}.8%</small></span></div>)}<div className="side-stat"><span>Total value locked</span><strong>$4.82B</strong></div></aside></div> }

const pools = [['ETH / USDC','28.42%','$184.6M'],['BNB / USDT','41.08%','$92.8M'],['ARB / ETH','46.18%','$72.1M'],['MATIC / USDC','19.75%','$38.9M']]
function PoolsView() { return <div className="page-view"><div className="page-title"><div><p className="eyebrow">Provide liquidity</p><h1>Liquidity Pools</h1><p>Put your assets to work and earn a share of trading fees.</p></div><button className="primary-button"><Plus /> Create position</button></div><ConfigNotice /> <div className="filter-bar"><button className="filter active">All pools</button><button className="filter">My positions</button><button className="filter">Stablecoins</button><span className="search-pill">Search pools</span></div><div className="pool-table">{pools.map((pool, index) => <div className="pool-row" key={pool[0]}><div className="pair"><span className="pair-icons"><span className={`token-icon ${tokens[index % 4].color}`}>{tokens[index % 4].glyph}</span><span className="token-icon usdc">$</span></span><strong>{pool[0]}</strong></div><div><small>APR</small><b className="positive">{pool[1]}</b></div><div><small>TVL</small><b>{pool[2]}</b></div><button className="outline-button">Add liquidity</button></div>)}</div></div> }

function CreatorView({ openWallet }: { openWallet: () => void }) { const [blockchain, setBlockchain] = useState('Ethereum'); return <div className="page-view narrow"><p className="eyebrow">Launch on-chain</p><h1>Create a token</h1><p>Deploy a standard ERC-20 token with your connected wallet. No hidden custody, no simulated receipts.</p><ConfigNotice kind="factory" /><div className="form-card"><label>Blockchain<select aria-label="Select blockchain" value={blockchain} onChange={(event) => setBlockchain(event.target.value)}><option>Ethereum</option><option>BNB Smart Chain</option><option>Polygon</option><option>Base</option></select></label><label>Token name<input placeholder="e.g. Juniper" /></label><label>Symbol<input placeholder="e.g. JNP" /></label><label>Total supply<input placeholder="1,000,000" /></label><label>Decimals<input value="18" readOnly /></label><button className="primary-button full" onClick={openWallet}><Wallet /> Connect wallet to deploy on {blockchain}</button></div></div> }
function GenericView({ title, eyebrow, description }: { title: string; eyebrow: string; description: string }) { return <div className="page-view empty-view"><Sparkles /><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p><div className="coming-pill">Module ready for contract configuration</div></div> }

export default function ExchangeApp() { const [view, setView] = useState('swap'); const [menu, setMenu] = useState(false); const [walletOpen, setWalletOpen] = useState(false); const { address, isConnected, chainId } = useAccount(); const { disconnect } = useDisconnect(); const { switchChain } = useSwitchChain(); const title = nav.find(([id]) => id === view)?.[1] ?? 'Swap';
 return <div className="dex-shell"><header className="topbar"><button className="brand" onClick={() => setView('home')}><span className="brand-mark"><Sparkles /></span><span>Exchange B2 Exchange<span className="brand-dot">.</span></span></button><nav className={menu ? 'main-nav open' : 'main-nav'}>{nav.map(([id, label, Icon]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => { setView(id); setMenu(false) }}><Icon />{label}</button>)}</nav><div className="top-actions"><label className="chain-select"><span className="chain-dot" />{chainId ? chainNames[chainId] : 'Ethereum'}<ChevronDown /><select aria-label="Select network" value={chainId ?? 1} onChange={(e) => switchChain({ chainId: Number(e.target.value) })}>{supportedChains.map((chain) => <option key={chain.id} value={chain.id}>{chain.name}</option>)}</select></label>{isConnected ? <button className="connect-button connected" onClick={() => disconnect()}><span className="live-dot" />{shortAddress(address)}</button> : <button className="connect-button" onClick={() => setWalletOpen(true)}><Wallet /> Connect wallet</button>}<button className="menu-button" onClick={() => setMenu(!menu)} aria-label="Toggle navigation"><Menu /></button></div></header><main className="main-content">{view === 'home' ? <div className="home-view"><div className="hero-copy"><span className="hero-kicker"><span className="live-dot" /> MULTI-CHAIN LIQUIDITY LAYER</span><h1>Markets that move<br /><em>with you.</em></h1><p>A sharper, quieter exchange for the on-chain economy. Swap assets, build liquidity, and launch what comes next.</p><div className="hero-actions"><button className="primary-button" onClick={() => setView('swap')}>Start trading <ArrowDownUp /></button><button className="outline-button" onClick={() => setView('pools')}>Explore pools <Droplets /></button></div></div><div className="hero-orb"><div className="orb-grid" /><div className="orb-core"><Sparkles /><b>JNP</b></div><span className="orb-token orb-one"><TokenIcon token={tokens[0]} /></span><span className="orb-token orb-two"><TokenIcon token={tokens[1]} /></span><span className="orb-token orb-three"><TokenIcon token={tokens[2]} /></span></div></div> : view === 'swap' ? <SwapView openWallet={() => setWalletOpen(true)} /> : view === 'pools' ? <PoolsView /> : view === 'create' ? <CreatorView openWallet={() => setWalletOpen(true)} /> : <GenericView title={title} eyebrow={title === 'History' ? 'Wallet activity' : 'Coming online'} description={`Explore ${title.toLowerCase()} across supported EVM networks. Connect contracts through the environment configuration to activate this module.`} />}</main><footer><span>JUNIPER PROTOCOL</span><span>Non-custodial · Open infrastructure</span><span>Network {chainId ?? 1} · <a href={address && chainId ? explorerUrl(chainId, address) : '#'}>Explorer <ExternalLink /></a></span></footer>{walletOpen && <WalletModal close={() => setWalletOpen(false)} />}</div> }
